hw1
Vazhid/vk_edu_cpp_projects pull request #1
Opened 2023-03-23 11:37 UTC by Vazhid

2023-03-23 19:29 UTC, ThCompiler requested changes
Как-то так

2023-03-23 19:29 UTC, ThCompiler commented on hw1/src/main.cpp
> +            if (static_cast<string>(argv[i]) == "--title-principals-path") {
а зачем тут приведение типов? справа же char*

2023-03-23 19:29 UTC, ThCompiler commented on hw1/src/main.cpp
> +string filename_with_persons;
а зачем их глобальные?

2023-03-23 19:29 UTC, ThCompiler commented on hw1/src/main.cpp
> +using namespace std;
Плохая практика, может приводить к ошибкам https://habr.com/ru/post/580204/

2023-03-23 19:29 UTC, ThCompiler commented on hw1/src/main.cpp
> +            cerr << "Where my arguments?" << endl;
Правда?) лучше говорить что не хватает а не спрашивать пользователя, он всё равно не сможет ответить

2023-03-23 19:29 UTC, ThCompiler commented on hw1/src/main.cpp
> +int main(int argc, char *argv[]) {
мейн можно разбить на пару функция. а для парсов аргументов есть штука под названием `getopt`

2023-03-23 19:29 UTC, ThCompiler commented on hw1/src/main.cpp
> +    nconst_search_by_name_in_file(names, tmp);
что такое nconst?

2023-03-23 19:29 UTC, ThCompiler commented on hw1/include/foo.hpp
> +void nconst_search_by_name_in_file(ifstream& file, person& pers);
лучше передавать более универсальный `istream`

2023-03-23 19:29 UTC, ThCompiler commented on hw1/include/foo.hpp
> +struct title {
структуры в плюсах именуются с припиской _t

2023-03-23 19:29 UTC, ThCompiler commented on hw1/src/foo.cpp
> +        vect_of_tokens = str_split_to_vect(str_input, '\t');
было бы удобно для чтения и понимания, если бы распаренная строка возвращалась в виде структуры, сразу понятно что является каким полем, а не просто индексы в массиве

2023-03-23 19:29 UTC, ThCompiler commented on hw1/src/foo.cpp
> +        if (vect_of_tokens[2] == pers.nconst && (vect_of_tokens[3] == "actor" || vect_of_tokens[3] == "actress")){
магические строки, потенциальная ошибка

2023-03-23 19:29 UTC, ThCompiler commented on hw1/src/main.cpp
> +        if (!tmp.titile_list[i].title_name.empty() && tmp.titile_list[i].is_movie) {
лучше добавить movie метод его валидации

2023-03-23 19:29 UTC, ThCompiler commented on hw1/src/foo.cpp
> +            if (vect_of_tokens[0] == pers.titile_list[i].tconst && vect_of_tokens[1] != "movie") {
можно обобщить, всё равно наличие title_name не повлияет, всё равно проверяешь по флагу

2023-03-24 08:45 UTC, Vazhid commented on hw1/src/foo.cpp
> +        if (vect_of_tokens[2] == pers.nconst && (vect_of_tokens[3] == "actor" || vect_of_tokens[3] == "actress")){
Их глобальными лучше сделать?

2023-03-27 19:26 UTC, ThCompiler requested changes

2023-03-27 19:26 UTC, ThCompiler commented on hw1/src/foo.cpp
> +    std::string name_flag = "name";
тогда уж глобальная константа лучше

2023-03-27 19:26 UTC, ThCompiler commented on hw1/include/foo.hpp
> +#pragma once
может более полезное название чем foo?

2023-03-27 19:26 UTC, ThCompiler commented on hw1/include/foo.hpp
> +void str_split(std::string& str, char sep, std::vector <std::string>& str_vect);
принято в конце файла ставить одну пустую строку

2023-03-27 19:26 UTC, ThCompiler commented on hw1/src/foo.cpp
> +            if (vect_of_tokens[PERSON_ID_INDEX_IN_LINKS] == pers.id &&
можно вынести в маленькие функции

2023-03-27 19:26 UTC, ThCompiler commented on hw1/src/main.cpp
> +    if (!tmp.id.empty()) {
лучше проверить что некорректно вывести и без блока else работать дальше иначе громоздишь вложенность лишнюю

2023-03-28 11:07 UTC, ThCompiler requested changes
ну и прошлый коммент остался

2023-03-28 11:07 UTC, ThCompiler commented on hw1/include/useful_utils.hpp
> +#pragma once
обычно в название пишут что делает данный код, плюс hpp и cpp называют одинаково если cpp реализуется то что объявлено в hpp

2023-05-14 13:04 UTC, romeokorovin commented on hw1/CMakeLists.txt
> +target_include_directories(hw1 PUBLIC include)
Часто принято в файлах оставлять в конце пустую строку. Даже гитлаб это принял как codestyle

2023-05-14 13:05 UTC, romeokorovin commented on hw1/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.0.0)
Прошу прощения - только сегодня заметил, что на образовательном портале есть вторая ветвь, куда попали вы и еще 2 студента. 
Поэтому проверяю ДЗ только сейчас, так как не знал о них
ДЗ2 буду проверять менее пристрастно, так как вы не могли учесть замечания из ДЗ1, которых тогда быть не могло

2023-05-14 13:05 UTC, romeokorovin commented on hw1/include/movie_data_processing.hpp
> +#define NAME_FLAG "name"
#define - это из языка С. Недостаток его в том, что тут не определяется тип, а типизиация важна для обнаружения ошибок при компиляции в С++
Для С++ следует стараться использовать inline const в заголовочном файле, а в cpp-файле - const <type>
Или constexpr

2023-05-14 13:06 UTC, romeokorovin commented on hw1/src/movie_data_processing.cpp
> +void str_split(std::string& str, char sep, std::vector <std::string>& str_vect) {
str следует указать как const

2023-05-14 13:08 UTC, romeokorovin commented on hw1/src/main.cpp
> +    for (size_t i = 0; i < tmp.titile_list.size(); i++) {
Желательно всегда использовать пре-инкремент, а не пост-инкремент (++i вместо i++) как более быструю операцию. Подробнее можно почитать, например, тут: https://stackoverflow.com/a/4445969

2023-05-14 13:08 UTC, romeokorovin commented on hw1/src/movie_data_processing.cpp
> +    return (title_type == MOVIE_COLNAME) ? true : false;
Можно упростить: 
return title_type == MOVIE_COLNAME;

2023-05-14 13:12 UTC, romeokorovin commented on hw1/CMakeLists.txt
> +add_executable(hw1 src/main.cpp src/functions.cpp)
Такого файла нет.

2023-05-14 13:15 UTC, romeokorovin commented on hw1/src/movie_data_processing.cpp
> +    while (c = (getopt_long_only(argc, argv, "", long_options, &option_index)) != -1)
Если передать дополнительный неправильный параметр, помимо обязательных, то программа падает 
./hw1: unrecognized option '--ii'
Segmentation fault (core dumped)

2023-05-14 13:23 UTC, romeokorovin commented on hw1/src/movie_data_processing.cpp
> +}
Не хватает примера
У меня не получилось вывести хоть что-то:
./hw1 --name Bruce --surname Lee --title-akas-path ../../../../title.akas.tsv --name-basics-path ../../../../name.basics.tsv --title-basics-path ../../../../title.basics.tsv --title-principals-path ../../../../title.principals.tsv
./hw1 --name Lee --surname Bruce --title-akas-path ../../../../title.akas.tsv --name-basics-path ../../../../name.basics.tsv --title-basics-path ../../../../title.basics.tsv --title-principals-path ../../../../title.principals.tsv
./hw1 --name Leonardo --surname DiCaprio --title-akas-path ../../../../title.akas.tsv --name-basics-path ../../../../name.basics.tsv --title-basics-path ../../../../title.basics.tsv --title-principals-path ../../../../title.principals.tsv

2023-06-05 19:53 UTC, merged