hw2
Vazhid/vk_edu_cpp_projects pull request #2
Opened 2023-04-11 13:36 UTC by Vazhid

2023-04-12 17:24 UTC, ThCompiler requested changes

2023-04-12 17:24 UTC, ThCompiler commented on hw2/include/commands_processing.hpp
> +void StrToVect(std::string& str, std::string& sep, const int sep_len, std::vector <std::string>& str_vect);
Пустая строка в конце файла нужна)

2023-04-12 17:24 UTC, ThCompiler commented on hw2/src/operations.cpp
> +void ReplaceOperation::ProcessLine(const std::string& str) {
у тебя вполне могут быть операции и после замены подстрок

2023-04-12 17:24 UTC, ThCompiler commented on hw2/src/main.cpp
> +        vect_of_oper_ptr[i]->SetNextOperation(*vect_of_oper_ptr[i + 1]);
ты сначала задёшь цепочку операций, а только потом вызываешь HandleEndOfInput

2023-04-12 17:24 UTC, ThCompiler commented on hw2/src/main.cpp
> +    std::vector<std::string> vect;
и всё это лучше вынести в отдельную функцию

2023-05-19 15:46 UTC, romeokorovin commented on hw2/CMakeLists.txt
> +add_executable(hw2 ${SRC_DIR}/main.cpp
Чтобы не перечислять множество файлов, можно использовать переменные. Примерно так
file(GLOB SOURCES " ${SRC_DIR}/*.cpp")
add_executable(hw2 ${SOURCES} ... )
В синтаксисе не совсем уверен, но там несложно

2023-05-19 15:50 UTC, romeokorovin commented on hw2/include/operations.hpp
> +    EchoOperation() : text_("") {}
Этот конструктор нигде не используется

2023-05-19 15:51 UTC, romeokorovin approved these changes

2023-05-19 15:51 UTC, romeokorovin commented on hw2/include/operations.hpp
> +    virtual void ProcessLine(const std::string&) = 0;
Есть правило - в случае переопределения базовых методов, нужно в базовом классе явно описывать виртуальный деструктор, если предполагается использование указателей базового класса для обращения к дочерним объектам.
Иначе при освобождении ресурсов будет вызван деструктор базового класса даже у дочерних
Подробнее: https://stackoverflow.com/questions/57275522/virtual-destructor-for-pure-abstract-class

2023-05-19 15:52 UTC, romeokorovin commented on hw2/include/operations.hpp
> + private:
private: - остался не у дел

2023-05-19 15:54 UTC, romeokorovin commented on hw2/src/commands_processing.cpp
> +std::vector<std::string> StrSplitToVect(const std::string& str, const std::string& sep, const int sep_len) {
Последний const - он не мешает, конечно же, но согласно устройству С++, это слово не меняет саму программу, так как параметр sep_len передаётся по значению, а не по ссылке. Т.е. если его изменить внутри функции, то это значение не вылезет наружу, так как будет изменена лишь копия.
Не ошибка, а лишь важно, чтобы вы это понимали

2023-05-21 11:06 UTC, romeokorovin commented on hw2/src/commands_processing.cpp
> +        if (operation.command == ECHO) {
Просто для информации: есть такой хитрый приём, когда операнды сравнения меняют местами
if (ECHO == operation.command)
Делается это для того, чтобы невозможно было опечататься = вместо ==
Дело в том, что в нынешней версии компилятор может и не заругаться на if (operation.command = ECHO), тогда как при обратном порядке точно будет ошибка присвоения значения литералу, т.е. программист сразу увидит опечатку

2023-05-21 11:10 UTC, romeokorovin commented on hw2/src/operations.cpp
> +    text_ = std::regex_replace(text_, std::regex(replaceable_), replacing_);
Получается, что особые символы типа ? или * будут обработаны по правилам регулярных выражений, а не как обычные символы. Это должно быть несколько неожиданно для пользователя

2023-05-21 11:15 UTC, romeokorovin commented on hw2/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.0.0)
./hw2 'echo 1 | echo 2'
1
2
По заданию, последний echo должен отбрасывать всё, что было до него

2023-05-21 11:17 UTC, romeokorovin commented on hw2/CMakeLists.txt
> +
Двойной cat зацикливается на своём первом значении

> cat cat23
cat2
cat3

./hw2 'echo 1 | cat cat1 | cat23'
1
cat1
cat1

2023-05-21 11:18 UTC, romeokorovin commented on hw2/CMakeLists.txt
> +
Дубль вывода при замене
 ./hw2 'echo 1 | cat cat23 | cat cat23 | replace at AT'
1
cat2
cat3
cat2
cat3
1
cAT2
cAT3
cAT2
cAT3

2023-06-05 19:54 UTC, merged